deploy script

diff --git a/server/scripts/project-deploy b/server/scripts/project-deploy
--- a/server/scripts/project-deploy
+++ b/server/scripts/project-deploy
@@ -1,25 +1,29 @@
 #!/bin/bash
 
-if [ $# -lt 1 ] || [ $# -gt 2 ]; then
+if [ $# -lt 1 ] || [ $# -gt 3 ]; then
   echo "Usage:"
-  echo "$0 <branch>"
-  echo "$0 <branch> <sub-domain|full-domain>"
+  echo "$0 <branch> <data-bucket?> <sub-domain|full-domain?>"
   exit 1
 fi
 
 branch=$1
-domain=$2
+dataBucketName=${2:-$branch}
+domain=$3
 projectName=$USER
 userDir="/home/$USER"
 
-# Ensure script is run from a user directory
 if [[ $PWD != $userDir ]]; then
   echo "Script must be run from a project user root."
   exit 1
 fi
 
+if [[ "dataBucketName" =~ [^a-zA-Z0-9_-] ]]; then
+  echo "Bucket name cannot contain special chars."
+  exit 1
+fi
+
 # Create variables
-dataDir="$userDir/data"
+baseDataDir="$userDir/data"
 tarFile="$userDir/artifacts/$branch.tar.gz"
 buildNumber=$(openssl rand -hex 8)
 destinationBuildDir="$userDir/builds/$branch-$buildNumber"
@@ -78,6 +82,10 @@ elif ! grep -q '^VIRTUAL_HOST=' $dotEnv; then
   exit 1
 fi
 
+# Remove pasta data from dot env and force it
+sed -i '/^PASTA_DATA=/d' $dotEnv
+echo "PASTA_DATA=../../data/$dataBucketName" >> $dotEnv
+
 # Set the docker compose project name from the unique build number
 # With this, "docker compose" commands can be ran from the branch link and the build directory
 composeProjectName="$USER_$branch_$buildNumber"
@@ -91,7 +99,7 @@ dataVolumes=$(echo "$dockerComposeConfig" | grep "source: $HOME/data" | awk -F"$
 # Create directories for each volume
 for volume in $dataVolumes; do
   echo "- $volume"
-  mkdir -p "${dataDir}${volume}"
+  mkdir -p "${baseDataDir}${volume}"
 done
 
 # FIXME : Maybe find something else than 777 ?
@@ -100,8 +108,8 @@ done
 # ADD : usermod -aG www-data $username
 # REMOVE : gpasswd -d $username www-data
 echo "Patching user on data ..."
-chown -R "$USER:$USER" $dataDir > /dev/null 2>&1
-chmod -R 0777 $dataDir > /dev/null 2>&1
+chown -R "$USER:$USER" $baseDataDir > /dev/null 2>&1
+chmod -R 0777 $baseDataDir > /dev/null 2>&1
 
 # Docker compose up
 echo "Starting containers ..."
